# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run . completion "bash" >./completions/agent-terminal.bash'
    - sh -c 'go run . completion "zsh" >./completions/agent-terminal.zsh'
    - sh -c 'go run . completion "fish" >./completions/agent-terminal.fish'
changelog:
  disable: true
builds:
  - binary: agent-terminal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - name_template: "agent-terminal-{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README.md
      - LICENSE-MIT
      - completions/*
      - src: extension/dist/chrome-mv3/*
        dst: extensions/chrome
      - src: extension/dist/agent-terminal-{{ .Version }}-firefox.zip
        dst: extensions/firefox.zip
release:
  prerelease: auto
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
brews:
  - name: agent-terminal
    homepage: https://github.com/pomdtr/tweety
    repository:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "agent-terminal"
      (share/"agent-terminal").install "extensions"
      bash_completion.install "completions/agent-terminal.bash"
      zsh_completion.install "completions/agent-terminal.zsh"
      fish_completion.install "completions/agent-terminal.fish"
    caveats: |
      After installation, run:
        agent-terminal install
      Then load the Chrome extension from share/agent-terminal/extensions/chrome
